"""Initial

Revision ID: ec941f1f8242
Revises: d4b7225d7ae2
Create Date: 2021-10-10 18:34:18.294594

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ec941f1f8242'
down_revision = 'd4b7225d7ae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plant_id'), 'plant', ['id'], unique=False)
    op.create_index(op.f('ix_plant_name'), 'plant', ['name'], unique=False)
    op.drop_index('ix_hero_age', table_name='hero')
    op.drop_index('ix_hero_id', table_name='hero')
    op.drop_index('ix_hero_name', table_name='hero')
    op.drop_index('ix_hero_secret_name', table_name='hero')
    op.drop_table('hero')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero',
    sa.Column('birth_date', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('secret_name', sa.VARCHAR(), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hero_secret_name', 'hero', ['secret_name'], unique=False)
    op.create_index('ix_hero_name', 'hero', ['name'], unique=False)
    op.create_index('ix_hero_id', 'hero', ['id'], unique=False)
    op.create_index('ix_hero_age', 'hero', ['age'], unique=False)
    op.drop_index(op.f('ix_plant_name'), table_name='plant')
    op.drop_index(op.f('ix_plant_id'), table_name='plant')
    op.drop_table('plant')
    # ### end Alembic commands ###
